name: Build Advanced PDF Tool EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      # 4️⃣ Clean previous builds (safe PowerShell)
      - name: Clean previous builds
        run: |
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
          Remove-Item -Force main.spec -ErrorAction SilentlyContinue
        shell: pwsh

      # 5️⃣ Build standalone EXE
      - name: Build EXE with hidden imports
        run: |
          pyinstaller --onefile --noconsole main.py \
                      --hidden-import=pkgutil \
                      --hidden-import=encodings \
                      --hidden-import=PyQt6.sip \
                      --hidden-import=fitz

      # 6️⃣ Upload EXE artifact
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdvancedPDFTool_EXE
          path: dist/main.exe
