name: Build Advanced PDF Tool EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
        shell: cmd

      # 4️⃣ Clean previous builds
      - name: Clean previous builds
        shell: pwsh
        run: |
          Remove-Item -Recurse -Force build -ErrorAction SilentlyContinue
          Remove-Item -Recurse -Force dist -ErrorAction SilentlyContinue
          Remove-Item -Force main.spec -ErrorAction SilentlyContinue

      # 5️⃣ Build standalone EXE with explicit name
      - name: Build EXE
        shell: cmd
        run: |
          pyinstaller --onefile --noconsole main.py --name AdvancedPDFTool --hidden-import=pkgutil --hidden-import=encodings --hidden-import=PyQt6.sip --hidden-import=fitz
          dir dist

      # 6️⃣ Upload EXE artifact
      - name: Upload EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: AdvancedPDFTool_EXE
          path: dist/AdvancedPDFTool.exe
